### ISSUE TITLE
Extreme instability in Consulo 2020.10 nightly

### ISSUE THREAD

**Issue by YT-GameWorks** [consulo/consulo#427] opened 2020-10-28 08:56 UTC
- IDE build number: 2020.10 #2716 nightly
- OS name and version: Windows 10 2004

I just opened a project and created a new java project and it crashed while indexing them both! Then I thought that I would let it index first then create the new project but that resulted in an even harder crash! Now it's been indexing for an hour and it's still going! I am unable to even switch back to release it is not letting me do anything other than open the IDE and then crash, @VISTALL I think this is because of that console switching thing that you made to fix  `Error on Console.Readkey();` in the DotNet repo because it is crashing in that same project! Hope this gets fixed quickly because I am unable to work or do anything!

Thanks!

**Comment by VISTALL** [comment] 2020-10-28 09:02
Please attach log

Help -> Show Log In Explorer.

**Comment by VISTALL** [comment] 2020-10-28 09:03
That why it's nightly. I on it, and don't have problems. Send me log, i will try to fix

**Comment by YT-GameWorks** [comment] 2020-10-28 09:27
When I switched to nightly I expected crashes on buttons and not this, I don't know why lol, anyway here are the [logs](https://uploadhub.co/e52de7008b9aae7b38d31c32932c56e8/consulo.log).

Also I don't know if this is related but an IDE error occured while I was getting the logs, Here

> com.google.gson.stream.MalformedJsonException: Unterminated object at line 13 column 6 path $.dependencies.: com.google.gson.stream.MalformedJsonException: Unterminated object at line 13 column 6 path $.dependencies.
> com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Unterminated object at line 13 column 6 path $.dependencies.
> 	at com.google.gson@2.8.6/com.google.gson.Gson.fromJson(Gson.java:947)
> 	at com.google.gson@2.8.6/com.google.gson.Gson.fromJson(Gson.java:870)
> 	at consulo.unity3d.packages.Unity3dManifest.lambda$parse$0(Unity3dManifest.java:69)
> 	at com.intellij.psi.impl.PsiCachedValueImpl.doCompute(PsiCachedValueImpl.java:54)
> 	at com.intellij.util.CachedValueBase.lambda$getValueWithLock$1(CachedValueBase.java:239)
> 	at com.intellij.openapi.util.RecursionManager$1.doPreventingRecursion(RecursionManager.java:114)
> 	at com.intellij.openapi.util.RecursionManager.doPreventingRecursion(RecursionManager.java:72)
> 	at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:240)
> 	at com.intellij.psi.impl.PsiCachedValueImpl.getValue(PsiCachedValueImpl.java:43)
> 	at com.intellij.util.CachedValuesManagerImpl.getCachedValue(CachedValuesManagerImpl.java:86)
> 	at com.intellij.psi.util.CachedValuesManager.getCachedValue(CachedValuesManager.java:122)
> 	at consulo.unity3d.packages.Unity3dManifest.parse(Unity3dManifest.java:60)
> 	at consulo.unity3d.UnityPluginValidator.notifyAboutPluginFile(UnityPluginValidator.java:96)
> 	at consulo.unity3d.UnityPluginValidator.lambda$runActivity$0(UnityPluginValidator.java:79)
> 	at consulo.ui.api@2-SNAPSHOT/consulo.ui.UIAccess.lambda$give$0(UIAccess.java:69)
> 	at consulo.ui.desktop.internal.AWTUIAccessImpl.lambda$give$0(AWTUIAccessImpl.java:53)
> 	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
> 	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
> 	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
> 	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
> 	at java.base/java.security.AccessController.doPrivileged(Native Method)
> 	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
> 	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
> 	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:793)
> 	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:704)
> 	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:394)
> 	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:703)
> 	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:393)
> 	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
> 	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
> 	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
> 	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
> 	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
> 	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
> Caused by: com.google.gson.stream.MalformedJsonException: Unterminated object at line 13 column 6 path $.dependencies.
> 	at com.google.gson@2.8.6/com.google.gson.stream.JsonReader.syntaxError(JsonReader.java:1564)
> 	at com.google.gson@2.8.6/com.google.gson.stream.JsonReader.doPeek(JsonReader.java:492)
> 	at com.google.gson@2.8.6/com.google.gson.stream.JsonReader.hasNext(JsonReader.java:415)
> 	at com.google.gson@2.8.6/com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:184)
> 	at com.google.gson@2.8.6/com.google.gson.internal.bind.MapTypeAdapterFactory$Adapter.read(MapTypeAdapterFactory.java:145)
> 	at com.google.gson@2.8.6/com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:131)
> 	at com.google.gson@2.8.6/com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:222)
> 	at com.google.gson@2.8.6/com.google.gson.Gson.fromJson(Gson.java:932)
> 	... 33 more
>  

Don't know if this helps or not but thanks!

**Comment by VISTALL** [comment] 2020-10-28 09:51
In your log too many exceptions of 

```
[ 709680]  ERROR - pi.editor.ex.util.SegmentArray - Invalid startOffset:-1 
java.lang.Throwable: null
	at consulo.logging.Logger.error(Logger.java:94) ~[Logger.class:?]
	at com.intellij.openapi.editor.ex.util.SegmentArray.setElementAt(SegmentArray.java:44) ~[PluginManagerCore.class:?]
```

That thing very old, and unstable. (reason idk can't catch and not reproducable)

Try drop cache 

File -> Invalidate Caches -> Invalidate Caches & Restart

If not help try drop directory like (C:\Users\VISTALL\AppData\Local\Consulo - here caches stored)

About unity crash. Can you show me what inside Packages/manifest.json file?

Thanks

**Comment by YT-GameWorks** [comment] 2020-10-28 09:55
>About unity crash. Can you show me what inside Packages/manifest.json file?

I didn't talk about a unity crash did I? anyway I'll try them both, I am currently in a class will do after an hour or so :)

Thanks !

**Comment by YT-GameWorks** [comment] 2020-10-28 09:56
unity never crashes with consulo :D

**Comment by VISTALL** [comment] 2020-10-28 09:59
```
com.google.gson.stream.MalformedJsonException: Unterminated object at line 13 column 6 path $.dependencies.: com.google.gson.stream.MalformedJsonException: Unterminated object at line 13 column 6 path $.dependencies.
com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Unterminated object at line 13 column 6 path $.dependencies.
at com.google.gson@2.8.6/com.google.gson.Gson.fromJson(Gson.java:947)
at com.google.gson@2.8.6/com.google.gson.Gson.fromJson(Gson.java:870)
at consulo.unity3d.packages.Unity3dManifest.lambda$parse$0(Unity3dManifest.java:69)
at
```

that thing is unity project startup validation.

**Comment by YT-GameWorks** [comment] 2020-10-28 10:00
> ```
> com.google.gson.stream.MalformedJsonException: Unterminated object at line 13 column 6 path $.dependencies.: com.google.gson.stream.MalformedJsonException: Unterminated object at line 13 column 6 path $.dependencies.
> com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Unterminated object at line 13 column 6 path $.dependencies.
> at com.google.gson@2.8.6/com.google.gson.Gson.fromJson(Gson.java:947)
> at com.google.gson@2.8.6/com.google.gson.Gson.fromJson(Gson.java:870)
> at consulo.unity3d.packages.Unity3dManifest.lambda$parse$0(Unity3dManifest.java:69)
> at
> ```
> 
> that thing is unity project startup validation.

weird, I did even start unity! I was just working on a stand-alone java project !

**Comment by VISTALL** [comment] 2020-10-28 10:04
> > ```
> > com.google.gson.stream.MalformedJsonException: Unterminated object at line 13 column 6 path $.dependencies.: com.google.gson.stream.MalformedJsonException: Unterminated object at line 13 column 6 path $.dependencies.
> > com.google.gson.JsonSyntaxException: com.google.gson.stream.MalformedJsonException: Unterminated object at line 13 column 6 path $.dependencies.
> > at com.google.gson@2.8.6/com.google.gson.Gson.fromJson(Gson.java:947)
> > at com.google.gson@2.8.6/com.google.gson.Gson.fromJson(Gson.java:870)
> > at consulo.unity3d.packages.Unity3dManifest.lambda$parse$0(Unity3dManifest.java:69)
> > at
> > ```
> > 
> > 
> > that thing is unity project startup validation.
> 
> weird, I did not even start unity! I was just working on a stand-alone java project !

maybe bug - will check. This check must be run only at unity project

**Comment by YT-GameWorks** [comment] 2020-10-28 10:05
oh, okay !

**Comment by YT-GameWorks** [comment] 2020-10-28 10:06
btw how to go back to release branch? should I just switch it in settings and then check for updates?

**Comment by VISTALL** [comment] 2020-10-28 10:10
> btw how to go back to release branch? should I just switch it in settings and then check for updates?

That thing harder =/ 

You need switch to release branch. Then drop platform directory (inside roaming dir https://github.com/consulo/EntryPoint/blob/master/boot/boot.directories.md)

And try start again - and call Check for updates.

In some cases plugins will not update, and need remove them and reinstall. 

(your crash is not related to nightly in 50% it will be return =/ try drop cache )

**Comment by VISTALL** [comment] 2020-10-28 10:11
Icon Theme is not supported at release branch

**Comment by YT-GameWorks** [comment] 2020-10-28 10:13
that's okay! My friend wanted to know how to and what I did, didn't work :D I stay on nightly

**Comment by VISTALL** [comment] 2020-10-28 10:17
Downgrade was requested but not easy task (https://github.com/consulo/consulo/issues/311)

**Comment by YT-GameWorks** [comment] 2020-10-28 10:56
Update:
Trying invalidate crashes and restart didn't work... Tried dropping that fit, didn't work ! It gets stuck indexing at 100% but then crashes!

**Comment by VISTALL** [comment] 2020-10-28 10:59
Thinking...

**Comment by YT-GameWorks** [comment] 2020-10-28 10:59
Let me try a reboot....

**Comment by VISTALL** [comment] 2020-10-28 11:24
Working on fix and adding debug. Bad luck for you.

I pushed commit, and run CI. I really want catch that thing

**Comment by VISTALL** [comment] 2020-10-28 11:25
waiting ci rebuild 

https://ci.consulo.io/

**Comment by YT-GameWorks** [comment] 2020-10-28 11:26
Update:
Tried reboot, kinda worked ! But not really stuck indexing at 100% but not crashed (yet)  oh never mind crashed while writing this lmao ! Think this is because it is loading into a project that has the unity editor plugin and the package.json has that modification that integrates consulo

**Comment by YT-GameWorks** [comment] 2020-10-28 11:28
Also found out why consulo was checking for unity project statup validation: it loaded a unity project without the editor running

**Comment by VISTALL** [comment] 2020-10-28 11:29
ignore unity file read, it's safe. can't affect any subsystems. (this error can be warn)

But index stucking is bad, i'm wanna find problem of it

**Comment by VISTALL** [comment] 2020-10-28 11:30
> Also found out why consulo was checking for unity project statup validation: it loaded a unity project without the editor running

yeah - it's not depend to editor. You have strange manifest file. Maybe with comments idk.

**Comment by YT-GameWorks** [comment] 2020-10-28 11:41
Stuck indexing System.Xml.dll don't know if this matter but this happned after I installed java and groovy and all the other nodes required for java and the consolu plugin devkit

**Comment by YT-GameWorks** [comment] 2020-10-28 11:42
I will reinstall consulo, see if that solve it

**Comment by VISTALL** [comment] 2020-10-28 11:43
Oh. You catch another problem. Can you attach log? 

Maybe it's .NET ASM library bug.

**Comment by VISTALL** [comment] 2020-10-28 11:48
> I will reinstall consulo, see if that solve it

You need drop all folders from wiki.

**Comment by VISTALL** [comment] 2020-10-28 12:04
Try to update.

**Comment by YT-GameWorks** [comment] 2020-10-28 12:25
> Oh. You catch another problem. Can you attach log?
> 
> Maybe it's .NET ASM library bug.

Yea sure, here are the [logs](https://github.com/consulo/consulo/files/5451761/consulo.Logs.txt)

**Comment by YT-GameWorks** [comment] 2020-10-28 12:25
> Try to update.

ok, lemme try

**Comment by VISTALL** [comment] 2020-10-28 12:26
Looks like no update 

![image](https://user-images.githubusercontent.com/542934/97435779-f89c0b00-1931-11eb-845d-43c746087cf1.png)

**Comment by YT-GameWorks** [comment] 2020-10-28 12:50
I don't get it! I am downloading those updates rn (internet here kinda slow so be right back after done )

**Comment by VISTALL** [comment] 2020-10-28 12:51
> I don't get it! I am downloading those updates rn (internet here kinda slow so be right back after done )

channel changed? 

link from hub

https://hub.consulo.io/api/repository/download?channel=nightly&platformVersion=2717&id=consulo-win64-zip&version=2717&platformBuildSelect=true

https://hub.consulo.io/#!repo/nightly/consulo-win64-zip

**Comment by YT-GameWorks** [comment] 2020-10-28 12:56
> > I don't get it! I am downloading those updates rn (internet here kinda slow so be right back after done )
> 
> channel changed?
> 
> link from hub
> 
> https://hub.consulo.io/api/repository/download?channel=nightly&platformVersion=2717&id=consulo-win64-zip&version=2717&platformBuildSelect=true
> 
> https://hub.consulo.io/#!repo/nightly/consulo-win64-zip

yes, channel=nightly ! bad news: Consulo isn't even opening after the update :( no errors nothing it is just not opening :[

**Comment by VISTALL** [comment] 2020-10-28 12:57
check process - maybe be it stucks

**Comment by YT-GameWorks** [comment] 2020-10-28 12:58
it is open in the background! lemme kill it and try again

**Comment by YT-GameWorks** [comment] 2020-10-28 13:00
didn't work :(

**Comment by YT-GameWorks** [comment] 2020-10-28 13:03
this is very weird, think need to do last resort! reinstall, but I sad bc I made a custom Dracula theme and it'll be lost! is there a way to uninstall consulo without killing that theme?

**Comment by VISTALL** [comment] 2020-10-28 13:04
> ${system-drive}/Users/${user-name}/AppData/Roaming/Consulo - configuration directory

this is settings directory.

Your scheme will be in child colorSchemes/ directory with your name

**Comment by VISTALL** [comment] 2020-10-28 13:06
For full reinstall drop all stored settings/caches

${system-drive}/Users/${user-name}/AppData/Roaming/Consulo - configuration directory
${system-drive}/Users/${user-name}/AppData/Roaming/Consulo Platorm - platform directory
${system-drive}/Users/${user-name}/AppData/Roaming/Consulo/plugins - plugin directory
${system-drive}/Users/${user-name}/AppData/Local/Consulo/log - log directory

**Comment by YT-GameWorks** [comment] 2020-10-28 13:06
Thanks a lot !

**Comment by YT-GameWorks** [comment] 2020-10-28 13:07
> For full reinstall drop all stored settings/caches
> 
> ${system-drive}/Users/${user-name}/AppData/Roaming/Consulo - configuration directory
> ${system-drive}/Users/${user-name}/AppData/Roaming/Consulo Platorm - platform directory
> ${system-drive}/Users/${user-name}/AppData/Roaming/Consulo/plugins - plugin directory
> ${system-drive}/Users/${user-name}/AppData/Local/Consulo/log - log directory

Should i delete the full Consulo directory in AppData?

**Comment by VISTALL** [comment] 2020-10-28 13:09
yh but save color scheme

**Comment by YT-GameWorks** [comment] 2020-10-28 13:10
ok, thanks !

**Comment by VISTALL** [comment] 2020-10-28 13:14
Can we go to Discord? :D it's hard to talk in that way (https://discord.gg/FeBfzJD)

**Comment by YT-GameWorks** [comment] 2020-10-28 13:14
Yay! I was in the middle of typing that !

**Closed** 2020-10-28 16:19 UTC
