### ISSUE TITLE
No variable with name "reference' in Debugger when watching variable

### ISSUE THREAD

**Issue by winalex** [consulo/consulo#173] opened 2016-03-27 18:58 UTC
Also showing wrong type of "reference" see testString
<img width="1388" alt="screen shot 2016-03-27 at 8 51 52 pm" src="https://cloud.githubusercontent.com/assets/689092/14067168/891d55ec-f45e-11e5-8d96-6084205305e2.png">
ComponentGroupReference and ComponentReference are subclass of ReferenceBase

**Comment by VISTALL** [comment] 2016-03-27 18:59
Already fixed with parameters

**Comment by winalex** [comment] 2016-03-27 19:05
Not fixed. I've latest update. Doesn't like word reference :dancer:

**Comment by VISTALL** [comment] 2016-03-27 19:22
this method contains yield ?

**Comment by winalex** [comment] 2016-03-27 19:31
No

**Comment by VISTALL** [comment] 2016-03-27 19:33
Idk how repeat it

**Comment by winalex** [comment] 2016-03-28 08:08
`class SomeEvent:UnityEvent<ReferenceBase>{}
class ReferenceBase:ScriptableObject{}
class ComponentReference:ReferenceBase{}
class ComponentGroupReference:ReferenceBase{}

class MyMono:MonoBehaviour{
void Awake(){
var someEvent=new SomeEvent();
someEvent.AddListener(Handler);
someEvent.Invoke(ScriptableObject.CreateInstance<ComponentReference>());
//Scriptable Object aren't created without "new" 
}
public void Handler(ReferenceBase reference){

//Add watch
    Debug.Log(reference.GetType());
reference=ScriptableObject.CreateInstance<ComponentGroupReference>();
  Debug.Log(reference.GetType());

}
}



`

Try this!

**Comment by VISTALL** [comment] 2016-03-28 08:54
Strange - i can't enter **Handler** method

![image](https://cloud.githubusercontent.com/assets/542934/14074715/d572f0b4-f4db-11e5-90ed-12022e1ed110.png)


when it call Invoke - no pause inside Handler

**Comment by winalex** [comment] 2016-03-28 08:57
what Logs print?

**Comment by VISTALL** [comment] 2016-03-28 08:58
Hm. That interest.

![image](https://cloud.githubusercontent.com/assets/542934/14074795/626cdf7a-f4dc-11e5-8663-928552393f22.png)

Why not paused. O_o

**Comment by winalex** [comment] 2016-03-28 09:04
Put breakpoint also on someEvent.Invoke then try get in or "Play" to next breakpoint

**Comment by VISTALL** [comment] 2016-03-28 09:12
Strange. I can't pause at any line, except *var someEvent = new SomeEvent();*

**Comment by VISTALL** [comment] 2016-03-28 09:17
ref https://github.com/consulo/consulo-dotnet/issues/69

**Closed by VISTALL** 2016-03-28 09:17 UTC
Labels: prio: normal, type: bug

**Comment by winalex** [comment] 2016-03-28 09:49
Don't close the previous issue as it is very important

**Comment by VISTALL** [comment] 2016-03-28 09:55
if i can't reproduce - i can't fix. There no other peoples to can test - except you
